[package]
name = "rinha2-back-end-bora-dale-xgh-rust"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.7", features = ["runtime-tokio-native-tls", "postgres", "json"] }
tokio = { version = "1", features = ["full"] }
once_cell = "1.17"